apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airbyte-02

bases:
  - ../../resources-dev

images:
  #- name: yuanrui2014/db
  #  newTag: dev
  - name: yuanrui2014/bootloader
    newTag: dev
  - name: yuanrui2014/server
    newTag: dev
  - name: yuanrui2014/webapp
    newTag: dev
  - name: yuanrui2014/worker
    newTag: dev
  - name: temporalio/auto-setup
    newTag: 1.7.0
  - name: yuanrui2014/cron
    newTag: dev

configMapGenerator:
  - name: airbyte-env
    env: .env

secretGenerator:
  - name: airbyte-secrets
    env: .secrets

patchesStrategicMerge:
  - parallelize-worker.yaml
