apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../resources-dev

images:
  - name: yuanrui2014/bootloader
    newTag: 2.0.1
  - name: yuanrui2014/server
    newTag: 2.0.1
  - name: yuanrui2014/webapp
    newTag: 2.0.1
  - name: yuanrui2014/worker
    newTag: 2.0.1
  - name: temporalio/auto-setup
    newTag: 1.13.0
  - name: yuanrui2014/cron
    newTag: 2.0.1

configMapGenerator:
  - name: airbyte-env
    env: .env

secretGenerator:
  - name: airbyte-secrets
    env: .secrets

patchesStrategicMerge:
  - parallelize-worker.yaml
