apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../resources-dev

images:
  - name: harbor.nekteck.cloud/airbyte/bootloader
    newTag: 0.0.51
  - name: harbor.nekteck.cloud/airbyte/server
    newTag: 0.0.51
  - name: harbor.nekteck.cloud/airbyte/webapp
    newTag: 0.0.51
  - name: harbor.nekteck.cloud/airbyte/worker
    newTag: 0.0.51
  - name: temporalio/auto-setup
    newTag: 1.13.0
  - name: harbor.nekteck.cloud/airbyte/cron
    newTag: 0.0.51

configMapGenerator:
  - name: airbyte-env
    env: .env

secretGenerator:
  - name: airbyte-secrets
    env: .secrets

patchesStrategicMerge:
  - parallelize-worker.yaml
